package com.example.socialnetwork.domain;

import java.io.Serializable;

public enum Command implements Serializable {
    REQUEST_MESSAGES_FOR_FRIENDSHIP,
    MESSAGES_FOR_FRIENDSHIP,
    REPLY_MESSAGE,
    REQUEST_MESSAGES,
    MESSAGES,
    REQUEST_MESSAGE,
    MESSAGE,
    ADD_MESSAGE,
    REQUEST_REQUEST,
    REQUEST,
    REQUEST_REQUESTS,
    REQUESTS,
    SEND_REQUEST,
    DELETE_REQUEST,
    ACCEPT_REQUEST,
    DECLINE_REQUEST,
    REQUEST_USER,
    USER,
    REQUEST_USERS,
    REQUEST_USER_BY_CREDENTIALS,
    REQUEST_USERS_PAGE,
    USERS,
    ADD_USER,
    DELETE_USER,
    UPDATE_USER,
    REQUEST_FRIENDSHIP,
    FRIENDSHIP,
    REQUEST_FRIENDSHIPS,
    FRIENDSHIPS,
    ADD_FRIENDSHIP,
    DELETE_FRIENDSHIP
}